# Generated by Django 5.2.3 on 2025-06-19 16:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('numero_mesa', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_sillas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'db_table': 'mesas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('direccion', models.TextField()),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_reporte', models.CharField(choices=[('Ventas', 'Ventas'), ('Compras', 'Compras'), ('Gastos', 'Gastos'), ('Nomina', 'Nomina'), ('Existencias', 'Existencias')], max_length=15)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_generacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id_tipo_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('metodo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de crédito', 'Tarjeta de crédito'), ('Nequi', 'Nequi'), ('Transferencia', 'Transferencia')], max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Pago',
                'verbose_name_plural': 'Tipos de Pago',
                'db_table': 'tipo_pago',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('direccion', models.TextField()),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'constraints': [models.UniqueConstraint(fields=('correo',), name='uq_cliente_correo')],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cargo', models.CharField(choices=[('Mesera', 'Mesera'), ('Barman', 'Barman'), ('Cajera', 'Cajera'), ('Administrador', 'Administrador')], max_length=20)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'constraints': [models.UniqueConstraint(fields=('correo',), name='uq_empleado_correo')],
            },
        ),
        migrations.CreateModel(
            name='MovimientosFinancieros',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10)),
                ('recibo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empleado')),
            ],
            options={
                'verbose_name': 'Movimiento Financiero',
                'verbose_name_plural': 'Movimientos Financieros',
                'db_table': 'movimientos_financieros',
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id_nomina', models.AutoField(primary_key=True, serialize=False)),
                ('salario_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empleado')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'db_table': 'nomina',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente')),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empleado')),
                ('id_mesa', models.ForeignKey(blank=True, db_column='id_mesa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mesas')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_pedido', models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pedido')),
                ('id_tipo_pago', models.ForeignKey(blank=True, db_column='id_tipo_pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipopago')),
            ],
            options={
                'verbose_name': 'Facturación',
                'verbose_name_plural': 'Facturaciones',
                'db_table': 'facturacion',
            },
        ),
        migrations.CreateModel(
            name='DescuentosPedido',
            fields=[
                ('id_descuento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('id_pedido', models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
            ],
            options={
                'verbose_name': 'Descuento de Pedido',
                'verbose_name_plural': 'Descuentos de Pedidos',
                'db_table': 'descuentos_pedido',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria')),
                ('id_marca', models.ForeignKey(blank=True, db_column='id_marca', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.marca')),
                ('id_proveedor', models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('id_pedido', models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_actual', models.IntegerField(blank=True, null=True)),
                ('fecha_recibido', models.DateField()),
                ('novedades', models.TextField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empleado')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto')),
                ('id_proveedor', models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='ReporteNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nomina', models.ForeignKey(db_column='id_nomina', on_delete=django.db.models.deletion.CASCADE, to='app.nomina')),
                ('id_reporte', models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, to='app.reportes')),
            ],
            options={
                'db_table': 'reporte_nomina',
                'unique_together': {('id_reporte', 'id_nomina')},
            },
        ),
        migrations.CreateModel(
            name='ReporteGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gasto', models.ForeignKey(db_column='id_gasto', on_delete=django.db.models.deletion.CASCADE, to='app.movimientosfinancieros')),
                ('id_reporte', models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, to='app.reportes')),
            ],
            options={
                'db_table': 'reporte_gastos',
                'unique_together': {('id_reporte', 'id_gasto')},
            },
        ),
        migrations.CreateModel(
            name='ReporteFacturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, to='app.facturacion')),
                ('id_reporte', models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, to='app.reportes')),
            ],
            options={
                'db_table': 'reporte_facturas',
                'unique_together': {('id_reporte', 'id_factura')},
            },
        ),
        migrations.CreateModel(
            name='ReporteCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, to='app.compra')),
                ('id_reporte', models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, to='app.reportes')),
            ],
            options={
                'db_table': 'reporte_compras',
                'unique_together': {('id_reporte', 'id_compra')},
            },
        ),
        migrations.CreateModel(
            name='ReporteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reporte', models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, to='app.reportes')),
                ('id_stock', models.ForeignKey(db_column='id_stock', on_delete=django.db.models.deletion.CASCADE, to='app.stock')),
            ],
            options={
                'db_table': 'reporte_stock',
                'unique_together': {('id_reporte', 'id_stock')},
            },
        ),
    ]
